name: 'Login and Push'
description: 'Login to Docker Hub then push builded image to repository'
inputs:
  DOCKERHUB_USERNAME:
    description: 'Docker Hub username'
    required: true
  DOCKERHUB_TAG:
    description: 'Tag to annotate image'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: "skunka/esgi-ci-cd:${{ inputs.DOCKERHUB_TAG }}"
