name: Bonjour
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
      types: [opened, synchronize, reopened, closed]
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm install
      - run: npm run lint
  container_test_job:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: docker image build --tag="${IMAGE_NAME}" .
      - run: docker container run --volume=./:/app "${IMAGE_NAME}" npm clean-install && npm run lint
      - uses: ./.github/actions/docker-login-push-action
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          DOCKERHUB_USERNAME: skunka
          DOCKERHUB_TAG: unstable
  docker_push:
    runs-on: ubuntu-22.04
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{  github.ref }}"
      - uses: ./.github/actions/docker-login-push-action
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          DOCKERHUB_USERNAME: skunka
          DOCKERHUB_TAG: ${{ github.ref_name }}
