name: Bonjour
on:
  - push
jobs:
  node_test:
    runs-on: ubuntu-22.04
    container:
      image: gitpod/workspace-node-22
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint